# $FreeBSD$
# Author: Shteryana Shopova <soc-shteryana@freebsd.org>

LIB=	bsnmptools

SRCS=	bsnmpimport.c bsnmpmap.c bsnmptools.c bsnmptc.c
INCS=	bsnmptools.h bsnmptc.h

MAN=	bsnmptools.3

.include <bsd.lib.mk>
